font:
  size: 12

software:
  darwin:
    taps:
      - homebrew/aliases
      - homebrew/bundle
      - oven-sh/bun
    brews:
      - chezmoi
      - git
      - gitleaks
      - gnupg
      - oven-sh/bun/bun
      - pass
      - pinentry-mac
      - volta
      - zsh
    casks:
      - balenaetcher
      - brave-browser
      # - docker
      - figma
      - font-noto-sans-mono
      - ghostty
      # - logi-options+
      - obsidian
      - raspberry-pi-imager
      - raycast
      - tailscale
      # - visual-studio-code
      # - vlc
      - warp
      # - yubico-authenticator
      # - yubico-yubikey-manager
      - zed
  linux_desktop:
    apts:
      - git
      - gnupg
      - pass
      - pcscd
      - scdaemon
      - ufw
    snaps:
      - brave
      - chezmoi --classic
      - obsidian --classic
    scripts:
      - name: bun
        value: curl -fsSL https://bun.sh/install | bash
      - name: volta
        value: curl https://get.volta.sh | bash
      - name: docker
        value: curl -fsSL https://get.docker.com | sh
      - name: tailscale
        value: curl -fsSL https://tailscale.com/install.sh | sh
