font:
  size: 12

software:
  brew:
    taps:
      - homebrew/aliases
      - homebrew/bundle
      - oven-sh/bun
    formulae:
      - chezmoi
      - fastfetch
      - git
      - gitleaks
      - gnupg
      - oven-sh/bun/bun
      - pass
      - pinentry-mac
      - volta
      - zsh
    casks:
      - balenaetcher
      - brave-browser
      - docker
      - figma
      - font-noto-sans-mono
      - ghostty
      - logi-options+
      - obsidian
      - raspberry-pi-imager
      - raycast
      - tailscale
      - visual-studio-code
      - vlc
      - warp
      # - yubico-authenticator
      # - yubico-yubikey-manager
      - zed
  linux:
    dpkgs:
      - git
      - gnupg
      - pass
      - pcscd
      - scdaemon
      - ufw
    snaps:
      - brave
      - chezmoi --classic
      - obsidian --classic
